services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "3080:3080"
    environment:
      - PORT=3080
    networks:
      - fpl-network

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://backend:3080
      - VITE_HOST=0.0.0.0
    networks:
      - fpl-network

networks:
  fpl-network:
    driver: bridge
